// =============================================================
//  Discrete Event Simulation — script.js
//  Parts 1 through 6 implemented from scratch (no frameworks)
// =============================================================

// ---------- Chart.js global defaults ----------
Chart.defaults.font.family = "'Inter', sans-serif";
Chart.defaults.color = '#64748b';
Chart.register(ChartDataLabels);

// Keep track of chart instances so we can destroy before redrawing
let ganttChart    = null;
let waitBarChart  = null;


// =============================================================
//  PART 1 — Linear Congruential Generator (LCG)
//  Formula : Xnext = (multiplier * Xcurrent + increment) mod modulus
//  Range   : value = (Xnext mod 10) + 1   →  gives [1 .. 10]
// =============================================================

const LCG_MULTIPLIER = 1664525;
const LCG_INCREMENT  = 1013904223;
const LCG_MODULUS    = 4294967296; // 2^32

// Returns the next LCG state.
// BigInt is used because  1664525 × 4294967295  overflows a JS float.
function lcgNextState(currentState) {
    const nextState = Number(
        (BigInt(LCG_MULTIPLIER) * BigInt(currentState) + BigInt(LCG_INCREMENT))
        % BigInt(LCG_MODULUS)
    );
    return nextState;
}

// Converts a raw LCG state to an integer in [1, 10]
function lcgToValue(state) {
    return (state % 10) + 1;
}


// =============================================================
//  PARTS 2, 3, 4, 5 — Simulation Engine
//  Supports: FCFS | LCFS | Priority  ×  1..N servers  +  warm-up
// =============================================================

function runSimulation(config) {

    // ----------------------------------------------------------
    //  STEP 1 — Generate random sequences via LCG  (Part 1)
    // ----------------------------------------------------------
    let lcgState = config.seed;           // reproducible starting point

    const interArrivalTimes = [];   // time between consecutive arrivals
    const serviceDurations  = [];   // how long each customer needs at the server
    const customerPriorities = [];  // 1 = highest, 3 = lowest

    for (let i = 0; i < config.numCustomers; i++) {
        lcgState = lcgNextState(lcgState);
        interArrivalTimes.push(lcgToValue(lcgState));

        lcgState = lcgNextState(lcgState);
        serviceDurations.push(lcgToValue(lcgState));

        // Priority also generated by LCG so results stay reproducible
        lcgState = lcgNextState(lcgState);
        customerPriorities.push((lcgState % 3) + 1);   // maps to 1, 2, or 3
    }

    // ----------------------------------------------------------
    //  STEP 2 — Build the list of customers with arrival times
    // ----------------------------------------------------------
    let clockAtArrival = 0;

    const customerList = interArrivalTimes.map((gap, index) => {
        clockAtArrival += gap;
        return {
            id              : index + 1,
            arrivalTime     : clockAtArrival,
            serviceTime     : serviceDurations[index],
            priority        : customerPriorities[index],
            // Fields filled in during simulation:
            serviceStartTime  : null,
            serviceEndTime    : null,
            servedByServer    : null,
            waitTimeInQueue   : null,   // time spent waiting before service starts
            waitTimeInSystem  : null,   // total time from arrival to departure
            wasRejected       : false
        };
    });

    // ----------------------------------------------------------
    //  STEP 3 — Run the simulation clock
    // ----------------------------------------------------------

    // serverFreeAt[i] = earliest time server i becomes free
    const serverFreeAt = Array(config.numServers).fill(0);

    // busyPeriods[i] = list of { start, end, customerId } for server i (used by Gantt)
    const busyPeriods = Array.from({ length: config.numServers }, () => []);

    let waitingQueue    = [];    // customers who arrived but haven't been served yet
    let nextToArrive    = 0;     // index into customerList
    let numProcessed    = 0;     // includes rejected customers
    let clock           = 0;
    let numRejected     = 0;

    const servedCustomers = [];  // successfully served customers, in service order

    while (numProcessed < config.numCustomers) {

        // 1. Add everyone who has arrived by now to the waiting queue
        while (nextToArrive < config.numCustomers &&
               customerList[nextToArrive].arrivalTime <= clock) {

            const arrivingCustomer = customerList[nextToArrive++];

            // Check if queue is full (0 = no limit)
            const busyServers  = serverFreeAt.filter(freeTime => freeTime > clock).length;
            const queueIsFull  = config.maxQueueSize > 0 &&
                                 waitingQueue.length >= config.maxQueueSize &&
                                 busyServers >= config.numServers;

            if (queueIsFull) {
                arrivingCustomer.wasRejected = true;
                numRejected++;
                numProcessed++;
            } else {
                waitingQueue.push(arrivingCustomer);
            }
        }

        // 2. Assign queued customers to free servers
        for (let serverIndex = 0; serverIndex < config.numServers; serverIndex++) {

            const serverIsFree = serverFreeAt[serverIndex] <= clock;
            if (!serverIsFree || waitingQueue.length === 0) continue;

            // Pick next customer based on queue discipline  (Part 4)
            let chosenCustomer;

            if (config.discipline === 'LCFS') {
                // Last-Come-First-Served: treat queue as a stack
                chosenCustomer = waitingQueue.pop();

            } else if (config.discipline === 'Priority') {
                // Priority queue: sort ascending by priority, then by arrival (FCFS tiebreak)
                waitingQueue.sort(
                    (a, b) => a.priority - b.priority || a.arrivalTime - b.arrivalTime
                );
                chosenCustomer = waitingQueue.shift();

            } else {
                // FCFS (default): take the one who arrived earliest
                chosenCustomer = waitingQueue.shift();
            }

            // Schedule the service
            const serviceStart = Math.max(clock, chosenCustomer.arrivalTime);
            const serviceEnd   = serviceStart + chosenCustomer.serviceTime;

            chosenCustomer.serviceStartTime = serviceStart;
            chosenCustomer.serviceEndTime   = serviceEnd;
            chosenCustomer.servedByServer   = serverIndex + 1;
            chosenCustomer.waitTimeInQueue  = serviceStart - chosenCustomer.arrivalTime;
            chosenCustomer.waitTimeInSystem = serviceEnd   - chosenCustomer.arrivalTime;

            serverFreeAt[serverIndex] = serviceEnd;
            busyPeriods[serverIndex].push({
                start      : serviceStart,
                end        : serviceEnd,
                customerId : chosenCustomer.id
            });

            servedCustomers.push(chosenCustomer);
            numProcessed++;
        }

        // 3. Advance the clock to the next meaningful event
        let nextEventTime = Infinity;

        if (nextToArrive < config.numCustomers) {
            nextEventTime = Math.min(nextEventTime, customerList[nextToArrive].arrivalTime);
        }
        for (let s = 0; s < config.numServers; s++) {
            if (serverFreeAt[s] > clock) {
                nextEventTime = Math.min(nextEventTime, serverFreeAt[s]);
            }
        }

        if (nextEventTime === Infinity) break;
        clock = nextEventTime;
    }

    // ----------------------------------------------------------
    //  Collect results
    // ----------------------------------------------------------

    // Sort served customers by id (they may have finished out of order)
    servedCustomers.sort((a, b) => a.id - b.id);

    // Merge served + rejected, sorted by id, for the event log table
    const rejectedCustomers = customerList.filter(c => c.wasRejected);
    const allCustomers      = [...servedCustomers, ...rejectedCustomers]
                              .sort((a, b) => a.id - b.id);

    // Total simulation time = when the last customer finishes
    const totalSimulationTime = Math.max(...servedCustomers.map(c => c.serviceEndTime), 0);

    // ----------------------------------------------------------
    //  STEP 4 — Compute stats, excluding warm-up customers (Part 5)
    // ----------------------------------------------------------
    const customersToAnalyze = servedCustomers.filter(c => c.id > config.warmupCount);

    if (customersToAnalyze.length === 0) {
        return {
            allCustomers, interArrivalTimes, serviceDurations,
            busyPeriods, numServers: config.numServers,
            warmupCount: config.warmupCount, numRejected,
            stats: {
                avgSystemWait  : 0,
                avgQueueLength : 0,
                utilization    : 0,
                perServerUtil  : [],
                totalTime      : totalSimulationTime
            }
        };
    }

    // W = average time a customer spends in the system
    const totalSystemWait  = customersToAnalyze.reduce((sum, c) => sum + c.waitTimeInSystem, 0);
    const avgSystemWait    = totalSystemWait / customersToAnalyze.length;

    // Q = average number of customers waiting in the queue
    const totalQueueWait   = customersToAnalyze.reduce((sum, c) => sum + c.waitTimeInQueue, 0);
    const avgQueueLength   = totalQueueWait / totalSimulationTime;

    // U = total busy time across all servers / (servers × simulation time)
    const allBusyTime      = busyPeriods.flat().reduce((sum, p) => sum + (p.end - p.start), 0);
    const utilization      = (allBusyTime / (totalSimulationTime * config.numServers)) * 100;

    // Per-server utilization (for the badges above the table)
    const perServerUtil = busyPeriods.map(periods => {
        const serverBusyTime = periods.reduce((sum, p) => sum + (p.end - p.start), 0);
        return totalSimulationTime > 0
            ? ((serverBusyTime / totalSimulationTime) * 100).toFixed(1)
            : '0.0';
    });

    return {
        allCustomers,
        interArrivalTimes,
        serviceDurations,
        busyPeriods,
        numServers   : config.numServers,
        warmupCount  : config.warmupCount,
        numRejected,
        stats: {
            avgSystemWait  : avgSystemWait.toFixed(3),
            avgQueueLength : avgQueueLength.toFixed(3),
            utilization    : utilization.toFixed(1),
            perServerUtil,
            totalTime      : totalSimulationTime
        }
    };
}


// =============================================================
//  Read config from the HTML form
// =============================================================

function readFormConfig() {
    return {
        numCustomers  : parseInt(document.getElementById('customerCount').value) || 15,
        seed          : parseInt(document.getElementById('seed').value)          || 42,
        numServers    : parseInt(document.getElementById('serverCount').value)   || 1,
        discipline    : document.getElementById('discipline').value,
        maxQueueSize  : parseInt(document.getElementById('maxQueue').value)      || 0,
        warmupCount   : parseInt(document.getElementById('warmup').value)        || 0
    };
}


// =============================================================
//  Update the KPI cards and event-log table
// =============================================================

function updateDashboard(result) {
    const stats = result.stats;

    // KPI cards
    document.getElementById('statW').innerText           = stats.avgSystemWait;
    document.getElementById('statQ').innerText           = stats.avgQueueLength;
    document.getElementById('statU').innerText           = stats.utilization + '%';
    document.getElementById('statTotalTime').innerText   = stats.totalTime;
    document.getElementById('statRejected').innerText    = result.numRejected;

    // LCG sequences
    document.getElementById('interArrivalSeq').innerText = result.interArrivalTimes.join(', ');
    document.getElementById('serviceSeq').innerText      = result.serviceDurations.join(', ');

    // Per-server utilization badges
    const serverUtilDiv = document.getElementById('perServerUtil');
    serverUtilDiv.innerHTML = stats.perServerUtil
        .map((util, i) => `<span class="badge bg-secondary me-1">S${i + 1}: ${util}%</span>`)
        .join('');

    // Event log table
    const tableBody    = document.querySelector('#simTable tbody');
    tableBody.innerHTML = '';

    const showPriorityColumn = document.getElementById('discipline').value === 'Priority';
    document.getElementById('priorityTh').style.display = showPriorityColumn ? '' : 'none';

    result.allCustomers.forEach(customer => {
        const row = document.createElement('tr');

        // Highlight warm-up rows and rejected rows differently
        if (customer.id <= result.warmupCount) row.classList.add('warmup-row');
        if (customer.wasRejected)              row.classList.add('table-danger');

        const queueWaitDisplay  = customer.wasRejected ? '—' : customer.waitTimeInQueue;
        const systemWaitDisplay = customer.wasRejected ? '—' : customer.waitTimeInSystem;
        const startDisplay      = customer.wasRejected ? '—' : customer.serviceStartTime;
        const endDisplay        = customer.wasRejected ? '—' : customer.serviceEndTime;

        const serverBadge = customer.wasRejected
            ? '<span class="badge bg-danger">Rejected</span>'
            : `<span class="badge bg-dark-soft">S${customer.servedByServer}</span>`;

        const priorityBadge = showPriorityColumn
            ? `<td><span class="badge ${
                customer.priority === 1 ? 'bg-danger' :
                customer.priority === 2 ? 'bg-warning text-dark' : 'bg-secondary'
              }">P${customer.priority}</span></td>`
            : '';

        const hasQueueWait = !customer.wasRejected && customer.waitTimeInQueue > 0;

        row.innerHTML = `
            <td><span class="fw-bold">#${customer.id}</span></td>
            <td>${result.interArrivalTimes[customer.id - 1]}</td>
            <td>${customer.arrivalTime}</td>
            <td>${customer.serviceTime}</td>
            <td>${startDisplay}</td>
            <td>${endDisplay}</td>
            <td class="${hasQueueWait ? 'text-primary fw-bold' : 'text-muted'}">${queueWaitDisplay}</td>
            <td>${systemWaitDisplay}</td>
            <td>${serverBadge}</td>
            ${priorityBadge}
        `;
        tableBody.appendChild(row);
    });
}


// =============================================================
//  PART 6 — Charts
// =============================================================

// Color palette — one color per server
const SERVER_COLORS = ['#4f46e5', '#10b981', '#f59e0b', '#ec4899', '#8b5cf6', '#06b6d4'];

function drawCharts(result) {
    const servedOnly = result.allCustomers.filter(c => !c.wasRejected);

    drawGanttChart(result, servedOnly);
    drawWaitBarChart(servedOnly);
}

// Gantt chart — shows busy/idle intervals for each server (Part 6)
function drawGanttChart(result, servedCustomers) {
    const ctx = document.getElementById('ganttChart').getContext('2d');
    if (ganttChart) ganttChart.destroy();

    // One row per server on the Y-axis
    const serverLabels = Array.from(
        { length: result.numServers },
        (_, i) => `Server ${i + 1}`
    );

    // One dataset per server so each gets its own colour
    const datasets = serverLabels.map((serverLabel, serverIndex) => ({
        label           : serverLabel,
        backgroundColor : SERVER_COLORS[serverIndex] || SERVER_COLORS[0],
        borderRadius    : 6,
        barPercentage   : 0.6,
        categoryPercentage: 0.8,
        data: servedCustomers
            .filter(c => c.servedByServer === serverIndex + 1)
            .map(c => ({
                x   : [c.serviceStartTime, c.serviceEndTime],   // bar spans [start, end]
                y   : serverLabel,
                label: `C${c.id}`                               // shown inside the bar
            }))
    }));

    ganttChart = new Chart(ctx, { type: 'bar',
        data: { labels: serverLabels, datasets },
        options: {
            indexAxis        : 'y',
            responsive       : true,
            maintainAspectRatio: false,
            plugins: {
                legend    : { position: 'top', align: 'end' },
                datalabels: {
                    display  : true,
                    color    : '#ffffff',
                    font     : { weight: 'bold', size: 10 },
                    formatter: value => value.label    // show customer ID inside bar
                },
                tooltip: {
                    callbacks: {
                        label: ctx => {
                            const bar = ctx.raw;
                            const duration = bar.x[1] - bar.x[0];
                            return `${bar.label}: starts ${bar.x[0]}, ends ${bar.x[1]}, duration ${duration}`;
                        }
                    }
                }
            },
            scales: {
                x: {
                    type : 'linear',
                    min  : 0,
                    title: { display: true, text: 'Simulation Time' },
                    grid : { color: '#f1f5f9' }
                },
                y: { type: 'category', labels: serverLabels }
            }
        }
    });
}

// Stacked bar chart — queue wait + service time per customer (Part 6)
function drawWaitBarChart(servedCustomers) {
    const ctx = document.getElementById('waitingChart').getContext('2d');
    if (waitBarChart) waitBarChart.destroy();

    const customerLabels = servedCustomers.map(c => `C${c.id}`);

    waitBarChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels  : customerLabels,
            datasets: [
                {label : 'Queue Wait',data : servedCustomers.map(c => c.waitTimeInQueue),backgroundColor: '#10b981',borderRadius:4},
                {label : 'Service Time',data : servedCustomers.map(c => c.serviceTime),backgroundColor: '#4f46e5',borderRadius:4}
            ]
        },
        options: {
            responsive       : true,
            maintainAspectRatio: false,
            plugins: {
                legend   : { position: 'top' },
                datalabels: {
                    display  : ctx => ctx.dataset.data[ctx.dataIndex] > 0,
                    color    : '#ffffff',
                    font     : { size: 9 }
                },
                title: {
                    display : true,
                    text    : 'System Wait per Customer  (Queue Wait + Service Time)'
                }
            },
            scales: {
                x: { stacked: true },
                y: { stacked: true, beginAtZero: true, title: { display: true, text: 'Time Units' } }
            }
        }
    });
}


// =============================================================
//  Auto-fill comparison tables  (Parts 3, 4, 5)
// =============================================================

function fillComparisonTables(baseConfig) {

    // ---- Part 3: Multi-server comparison (FCFS, no warm-up for fair baseline) ----
    [1, 2, 3].forEach(numServers => {
        const result = runSimulation({ ...baseConfig, numServers, warmupCount: 0, discipline: 'FCFS' });
        document.getElementById(`msc-w${numServers}`).innerText = result.stats.avgSystemWait;
        document.getElementById(`msc-q${numServers}`).innerText = result.stats.avgQueueLength;
        document.getElementById(`msc-u${numServers}`).innerText = result.stats.utilization + '%';
    });

    // ---- Part 4: Discipline comparison (FCFS vs LCFS, same seed) ----
    const fcfsResult = runSimulation({ ...baseConfig, discipline: 'FCFS' });
    const lcfsResult = runSimulation({ ...baseConfig, discipline: 'LCFS' });

    document.getElementById('dc-fcfs-w').innerText = fcfsResult.stats.avgSystemWait;
    document.getElementById('dc-fcfs-q').innerText = fcfsResult.stats.avgQueueLength;
    document.getElementById('dc-lcfs-w').innerText = lcfsResult.stats.avgSystemWait;
    document.getElementById('dc-lcfs-q').innerText = lcfsResult.stats.avgQueueLength;

    const wDifference = (parseFloat(lcfsResult.stats.avgSystemWait)  - parseFloat(fcfsResult.stats.avgSystemWait)).toFixed(3);
    const qDifference = (parseFloat(lcfsResult.stats.avgQueueLength) - parseFloat(fcfsResult.stats.avgQueueLength)).toFixed(3);
    document.getElementById('dc-diff-w').innerText = (wDifference >= 0 ? '+' : '') + wDifference;
    document.getElementById('dc-diff-q').innerText = (qDifference >= 0 ? '+' : '') + qDifference;

    // ---- Part 5: Warm-up comparison (k=0 vs k=3) ----
    const noWarmup   = runSimulation({ ...baseConfig, warmupCount: 0 });
    const withWarmup = runSimulation({ ...baseConfig, warmupCount: 3 });

    document.getElementById('wuc-w0').innerText = noWarmup.stats.avgSystemWait;
    document.getElementById('wuc-w3').innerText = withWarmup.stats.avgSystemWait;
    document.getElementById('wuc-wd').innerText = (withWarmup.stats.avgSystemWait  - noWarmup.stats.avgSystemWait).toFixed(3);

    document.getElementById('wuc-q0').innerText = noWarmup.stats.avgQueueLength;
    document.getElementById('wuc-q3').innerText = withWarmup.stats.avgQueueLength;
    document.getElementById('wuc-qd').innerText = (withWarmup.stats.avgQueueLength - noWarmup.stats.avgQueueLength).toFixed(3);

    document.getElementById('wuc-u0').innerText = noWarmup.stats.utilization  + '%';
    document.getElementById('wuc-u3').innerText = withWarmup.stats.utilization + '%';
    document.getElementById('wuc-ud').innerText = (withWarmup.stats.utilization - noWarmup.stats.utilization).toFixed(1) + '%';
}


// =============================================================
//  Entry point — called when the form is submitted
// =============================================================

function onFormSubmit(event) {
    if (event) event.preventDefault();

    const config = readFormConfig();
    const result = runSimulation(config);

    updateDashboard(result);
    drawCharts(result);
    fillComparisonTables(config);
}

// Wire up events
document.getElementById('simForm').addEventListener('submit', onFormSubmit);
document.getElementById('resetBtn').addEventListener('click', () => location.reload());
document.addEventListener('DOMContentLoaded', () => onFormSubmit());
